name: NestJS CI/CD

on:
  workflow_call:
    inputs:
      environment: # 'prd' ou 'hml'
        required: true
        type: string
      gh_environment:
        required: true
        type: string
      project_id:
        required: true
        type: string
      region:
        default: 'southamerica-east1'
        type: string
      image_name:
        required: true
        type: string
      repo_name:
        required: true
        type: string
      node_version:
        default: 20
        type: number
    outputs:
      version:
        value: ${{ jobs.code-validations.outputs.version }}
    secrets:
      WIF_PROVIDER:
        required: true
      WIF_SERVICE_ACCOUNT:
        required: true

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  code-validations:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      skip_deploy: ${{ steps.version.outputs.skip_deploy }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: 'npm'

      - name: Version Check
        id: version
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "skip_deploy=false" >> $GITHUB_OUTPUT
          
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            if [[ $VERSION == *"-rc"* ]] || [[ $VERSION == *"-alpha"* ]] || [[ $VERSION == *"-beta"* ]]; then
              echo "❌ Error: Stable version required for Master." && exit 1
            fi
            
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            if [[ $VERSION != *"-rc"* ]] && [[ $VERSION != *"-alpha"* ]] && [[ $VERSION != *"-beta"* ]]; then
              echo "⚠️ Stable version ($VERSION) detected on develop!"
              
              git fetch --tags
              if git rev-parse "v$VERSION" >/dev/null 2>&1; then
                 echo "❌ Error: Version v$VERSION already exists. Increment the version in package.json." && exit 1
              fi
              
              PR_EXISTS=$(gh pr list --head develop --base master --state open --json number | jq '. | length')
              
              if [ "$PR_EXISTS" -eq "0" ]; then
                echo "🚀 Creating automatic Pull Request for master..."
                gh pr create --base master --head develop --title "🚀 Release v$VERSION" --body "Release automatizada gerada a partir da branch develop para a versão **v$VERSION**."
              else
                echo "⚠️ A Pull Request from develop to master already exists. Updating code there."
              fi

              echo "skip_deploy=true" >> $GITHUB_OUTPUT
              exit 0
            fi
          else
            if [[ $VERSION != *"-rc"* ]] && [[ $VERSION != *"-alpha"* ]] && [[ $VERSION != *"-beta"* ]]; then
              echo "❌ Error: Development versions must have -rc, -alpha or -beta suffix." && exit 1
            fi
          fi

      - name: Install & Test
        if: steps.version.outputs.skip_deploy != 'true'
        run: |
          npm ci
          npm test -- --watchAll=false

  docker-validations:
    needs: code-validations
    if: needs.code-validations.outputs.skip_deploy != 'true'
    runs-on: ubuntu-latest

    environment: ${{ inputs.gh_environment }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Auth to GCP (WIF)
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Check if Image Exists
        run: |
          IMAGE="${{ inputs.region }}-docker.pkg.dev/${{ inputs.project_id }}/${{ inputs.repo_name }}/${{ inputs.image_name }}:${{ needs.code-validations.outputs.version }}"
          if gcloud artifacts docker images describe $IMAGE >/dev/null 2>&1; then
            echo "❌ Error: Version ${{ needs.code-validations.outputs.version }} already exists in Registry." && exit 1
          fi

      - name: Build and Push Docker
        run: |
          TAG="${{ inputs.region }}-docker.pkg.dev/${{ inputs.project_id }}/${{ inputs.repo_name }}/${{ inputs.image_name }}:${{ needs.code-validations.outputs.version }}"

          BUILD_ID=$(gcloud builds submit --tag $TAG --async --format='value(id)' .)
          echo "Build iniciado com ID: $BUILD_ID"
          
          echo "Aguardando conclusão do build..."
          gcloud builds wait $BUILD_ID --project=${{ inputs.project_id }}
          echo "Docker image $TAG criada e enviada para o Artifact Registry com sucesso!"

  deploy-on-gcp:
    needs: [code-validations, docker-validations]
    if: needs.code-validations.outputs.skip_deploy != 'true'
    runs-on: ubuntu-latest

    environment: ${{ inputs.gh_environment }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Auth to GCP (WIF)
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
      - name: Deploy to Cloud Run
        run: |
          sed -i "s|IMAGE_TAG_PLACEHOLDER|${{ needs.code-validations.outputs.version }}|g" infra/service-${{ inputs.environment }}.yaml

          gcloud run services replace infra/service-${{ inputs.environment }}.yaml --region ${{ inputs.region }}

      - name: Create Git Tag
        run: |
          git tag v${{ needs.code-validations.outputs.version }}
          git push origin v${{ needs.code-validations.outputs.version }}